//! Replay Quint-generated JIT runtime traces against the Rust model.
//!
//! Traces are expected in JSON format at spec/quint/traces/*.json,
//! generated by:
//!   quint run --out-itf=spec/quint/traces/trace.json jit_runtime.qnt
//!
//! Each trace is a sequence of steps: { "action": "call"|"redefine"|"deopt", "func": "f" }

use rele_elisp_spec_tests::replay::{self, JitState, TraceStep};

/// Verify the Rust state machine model satisfies invariants on a hand-written trace.
#[test]
fn hand_written_call_compile_deopt_cycle() {
    let steps = vec![
        TraceStep {
            action: "call".into(),
            func: "f".into(),
        },
        TraceStep {
            action: "call".into(),
            func: "f".into(),
        },
        TraceStep {
            action: "call".into(),
            func: "f".into(),
        },
        // f should now be Compiled (threshold=3)
        TraceStep {
            action: "deopt".into(),
            func: "f".into(),
        },
        // f falls back to Interp, but compiled code stays in cache
        TraceStep {
            action: "call".into(),
            func: "f".into(),
        },
        // f should be Compiled again (cache still valid)
    ];

    let result = replay::replay_trace(&steps, 3);
    assert!(result.is_none(), "invariant violation: {result:?}");
}

#[test]
fn redefine_invalidates_compiled_code() {
    let steps = vec![
        // Compile f
        TraceStep {
            action: "call".into(),
            func: "f".into(),
        },
        TraceStep {
            action: "call".into(),
            func: "f".into(),
        },
        TraceStep {
            action: "call".into(),
            func: "f".into(),
        },
        // f is now Compiled
        TraceStep {
            action: "redefine".into(),
            func: "f".into(),
        },
        // f should be Interp, cache invalidated
        TraceStep {
            action: "call".into(),
            func: "f".into(),
        },
        // f should still be Interp (counter reset, only 1 call)
    ];

    let result = replay::replay_trace(&steps, 3);
    assert!(result.is_none(), "invariant violation: {result:?}");
}

#[test]
fn redefine_during_warmup_resets_counter() {
    let steps = vec![
        TraceStep {
            action: "call".into(),
            func: "g".into(),
        },
        TraceStep {
            action: "call".into(),
            func: "g".into(),
        },
        // g has 2 calls, about to hit threshold
        TraceStep {
            action: "redefine".into(),
            func: "g".into(),
        },
        // Counter reset
        TraceStep {
            action: "call".into(),
            func: "g".into(),
        },
        TraceStep {
            action: "call".into(),
            func: "g".into(),
        },
        // g has 2 calls again (not 4), still below threshold=3
    ];

    let result = replay::replay_trace(&steps, 3);
    assert!(result.is_none(), "invariant violation: {result:?}");
}

#[test]
fn multiple_functions_independent() {
    let steps = vec![
        TraceStep {
            action: "call".into(),
            func: "f".into(),
        },
        TraceStep {
            action: "call".into(),
            func: "g".into(),
        },
        TraceStep {
            action: "call".into(),
            func: "f".into(),
        },
        TraceStep {
            action: "call".into(),
            func: "f".into(),
        },
        // f compiled, g still warming up
        TraceStep {
            action: "redefine".into(),
            func: "f".into(),
        },
        // f invalidated, g unaffected
        TraceStep {
            action: "call".into(),
            func: "g".into(),
        },
        TraceStep {
            action: "call".into(),
            func: "g".into(),
        },
        // g compiled now
    ];

    let result = replay::replay_trace(&steps, 3);
    assert!(result.is_none(), "invariant violation: {result:?}");
}

/// Verify invariant accessors directly on the Rust model.
#[test]
fn state_machine_invariants_unit() {
    let mut state = JitState::new(&["f", "g", "h"], 3);

    // Initial state satisfies both invariants
    assert!(state.check_safe_execution());
    assert!(state.check_no_stale_keeps_running());

    // Warm up and compile f
    state.call("f");
    state.call("f");
    state.call("f");
    assert!(state.check_safe_execution());

    // Redefine: must invalidate
    state.redefine("f");
    assert!(state.check_safe_execution());
    assert!(state.check_no_stale_keeps_running());
}
